// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xUeco6U5Cw5EEoed5xFiaB1ONOy3uFY',
    appId: '1:446389938654:web:1f3a17d12b85240c26d54f',
    messagingSenderId: '446389938654',
    projectId: 'infit-7aa88',
    authDomain: 'infit-7aa88.firebaseapp.com',
    storageBucket: 'infit-7aa88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjIE7UWDm8v2v_65Si0SgJopQDr9xurWM',
    appId: '1:446389938654:android:7752ddb80875bb7d26d54f',
    messagingSenderId: '446389938654',
    projectId: 'infit-7aa88',
    storageBucket: 'infit-7aa88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6XZmCgNoIk1qniqcQoRVoFYNOZHz6IbU',
    appId: '1:446389938654:ios:769f32d3845f8a6c26d54f',
    messagingSenderId: '446389938654',
    projectId: 'infit-7aa88',
    storageBucket: 'infit-7aa88.appspot.com',
    iosClientId: '446389938654-v32b2a50ofl9u69g3obbkas4gjja8pqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6XZmCgNoIk1qniqcQoRVoFYNOZHz6IbU',
    appId: '1:446389938654:ios:769f32d3845f8a6c26d54f',
    messagingSenderId: '446389938654',
    projectId: 'infit-7aa88',
    storageBucket: 'infit-7aa88.appspot.com',
    iosClientId: '446389938654-v32b2a50ofl9u69g3obbkas4gjja8pqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
